services:
  - type: web
    name: filla-backend
    env: python
    runtime: python-3.11.9
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port 10000